# =============================================================================
# AgileIQ — AI-Powered Sprint Intelligence System
# Phase: Phase 3 — AI Build
# Description: Sends sprint standup notes to Google Gemini API and generates
#              a structured, stakeholder-ready sprint status report.
#              Includes rule-based blocker detection layer.
# =============================================================================

from google import genai
from google.genai import types
import os
import sys                          # ← ADDED: needed to read command-line argument
from dotenv import load_dotenv
load_dotenv()

# =============================================================================
# SECTION 1: CONFIGURATION
# =============================================================================

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise EnvironmentError(
        "GEMINI_API_KEY environment variable not set. "
        "Please set it before running this script.\n"
        "Mac/Linux: export GEMINI_API_KEY='your-key-here'\n"
        "Windows:   set GEMINI_API_KEY=your-key-here"
    )

client = genai.Client(api_key=GEMINI_API_KEY)

# =============================================================================
# SECTION 2: INPUT — Read Standup Notes from File
# =============================================================================
# The script accepts a file path as a command-line argument.
# Usage: python agileiq_reporter.py test_inputs/scenario_01_healthy.txt
#
# This is Phase 3 testing mode — input comes from a local .txt file.
# In production (Phase 3 final), this section will be replaced with
# a webhook receiver from OttoKit, which will POST the standup notes
# directly to this script. The rest of the pipeline stays identical.
# =============================================================================

if len(sys.argv) < 2:
    print("=" * 60)
    print("  AgileIQ — Usage Error")
    print("=" * 60)
    print("\n  Please provide a standup notes file as an argument.")
    print("  Example: python agileiq_reporter.py test_inputs/scenario_01_healthy.txt\n")
    sys.exit(1)

input_file = sys.argv[1]

if not os.path.exists(input_file):
    print(f"\n  ❌ File not found: {input_file}")
    print("  Please check the file path and try again.\n")
    sys.exit(1)

with open(input_file, "r", encoding="utf-8") as f:
    standup_notes = f.read()

# =============================================================================
# SECTION 3: PROMPT ENGINEERING — System Prompt for Gemini
# =============================================================================
# This prompt defines Gemini's role, output structure, and quality rules.
# It is the core intelligence layer of AgileIQ.
# Well-crafted prompts produce consistent, stakeholder-ready reports.
# =============================================================================

SYSTEM_PROMPT = """
You are AgileIQ — an expert AI Sprint Reporting Assistant embedded in an Agile software team.

Your role is to analyse raw sprint standup notes provided by the Project Manager and produce a clear, professional, stakeholder-ready Weekly Sprint Status Report.

You must follow these rules without exception:
1. Base your report ONLY on what is explicitly stated in the standup notes. Do not invent or assume information.
2. Use professional business language. Avoid jargon. Write for an executive audience.
3. Flag every blocker, risk, and dependency explicitly — these are the most critical items for stakeholders.
4. Apply RAG (Red / Amber / Green) status with precision:
   - RED: Sprint goal is at immediate risk. A blocker is active and unresolved with no clear resolution timeline.
   - AMBER: Sprint goal may be at risk. A blocker exists but is being managed, or a risk has been flagged but not yet materialised.
   - GREEN: Sprint is on track. No active blockers. Delivery is expected as planned.
5. Be concise. Each section should be readable in under 60 seconds.
6. Always include a Recommendations section with at least 2 specific, actionable items for the PM.

OUTPUT FORMAT — You must produce the report in exactly this structure:

---

# AgileIQ Weekly Sprint Status Report
**Project:** [Extract from notes]
**Sprint:** [Extract from notes]
**Report Period:** [Extract from notes]
**Generated by:** AgileIQ AI Sprint Intelligence System

---

## 1. Sprint Summary
A 3–5 sentence narrative overview of the sprint week. Cover overall progress, team activity, and general health. Do not list every task — synthesise the pattern.

---

## 2. Team Progress Snapshot
A brief bullet for each team member (Name — Role: one sentence on their week's progress).

---

## 3. Blockers Flagged 🚨
For each blocker identified:
- **[Team Member / Area]:** Description of the blocker.
  - Status: Active / Escalated / Resolved
  - Impact: What does this block? Which user stories or sprint goals are affected?
  - Days Active: [Number]
  - Owner: Who is responsible for resolution?

If no blockers: write "No active blockers this week."

---

## 4. Risks & Dependencies ⚠️
List any flagged risks or inter-team dependencies that are not yet blockers but could become ones. Include likelihood and potential impact.

---

## 5. RAG Status
**Overall Sprint RAG: [RED / AMBER / GREEN]**
**Justification:** A 2–3 sentence explanation of why this RAG status was assigned, referencing specific evidence from the standup notes.

---

## 6. Recommendations
Numbered list of 2–4 specific, actionable recommendations for the PM or Scrum Master. Be direct. Each recommendation should name the action, the owner, and the timeframe.

---

## 7. Next Steps
2–3 bullet points summarising the most critical items to resolve or monitor in the coming week.

---
"""

# =============================================================================
# SECTION 4: BLOCKER DETECTION — Rule-Based Keyword Scanner
# =============================================================================
# This function runs BEFORE the AI call.
# It scans standup notes for known blocker keywords and prints a
# BLOCKERS FLAGGED section immediately — no AI required, instant, reliable.
# Filters out "Blockers: None" lines so only real issues are surfaced.
# =============================================================================

def detect_blockers(notes: str) -> list:
    """
    Scans standup notes for blocker keywords.
    Filters out lines that say 'none' (i.e. no blocker reported).
    Returns a list of lines containing genuine blocker language.

    Args:
        notes: The raw standup notes string.

    Returns:
        A list of lines that contain a blocker keyword but are NOT 'none' lines.
    """
    keywords = ["blocked", "blocker", "delay", "dependency", "waiting on"]

    # Phrases that indicate NO blocker — filter these out
    none_phrases = ["none.", "none currently", "blockers: none", "no blockers"]

    flagged_lines = []

    for line in notes.strip().split("\n"):
        line_lower = line.lower()

        # Skip blank or very short lines
        if not line.strip() or len(line.strip()) < 10:
            continue

        # Skip lines that are just saying "no blocker"
        if any(phrase in line_lower for phrase in none_phrases):
            continue

        # Flag lines that contain a blocker keyword
        if any(keyword in line_lower for keyword in keywords):
            flagged_lines.append(line.strip())

    return flagged_lines


# =============================================================================
# SECTION 5: AI CALL — Send Notes to Gemini and Generate Report
# =============================================================================

def generate_sprint_report(notes: str, system_prompt: str) -> str:
    """
    Sends standup notes to Google Gemini and returns a formatted sprint report.

    Args:
        notes: The raw standup notes string.
        system_prompt: The structured prompt defining output format and rules.

    Returns:
        The AI-generated sprint status report as a string.
    """
    user_message = f"""
Please analyse the following sprint standup notes and produce a Weekly Sprint Status Report
following the format and rules in your instructions.

STANDUP NOTES:
{notes}
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        config=types.GenerateContentConfig(
            system_instruction=system_prompt,
        ),
        contents=user_message,
    )

    return response.text


# =============================================================================
# SECTION 6: MAIN — Run the Full AgileIQ Pipeline
# =============================================================================
# Execution order:
#   1. Rule-based blocker detection  (instant, no API needed)
#   2. Gemini API call               (AI-generated full report)
#   3. Print both to terminal
#   4. Save the AI report to a .md file for portfolio evidence
# =============================================================================

if __name__ == "__main__":

    print("=" * 60)
    print("  AgileIQ — AI-Powered Sprint Intelligence System")
    print("=" * 60)
    print(f"\n  📂 Input file: {input_file}\n")      # ← shows which file was loaded

    # ------------------------------------------------------------------
    # STEP 1: Rule-based blocker detection (runs before the AI call)
    # ------------------------------------------------------------------
    print("\n⚠️  STEP 1: RULE-BASED BLOCKER DETECTION")
    print("-" * 60)

    flagged = detect_blockers(standup_notes)

    if flagged:
        print(f"  {len(flagged)} genuine blocker(s) detected:\n")
        for i, line in enumerate(flagged, 1):
            print(f"  {i}. {line}")
    else:
        print("  ✅ No blockers detected in standup notes.")

    print()

    # ------------------------------------------------------------------
    # STEP 2: Send to Gemini API and generate the full AI report
    # ------------------------------------------------------------------
    print("🤖  STEP 2: SENDING TO GEMINI API...")
    print("-" * 60)

    report = generate_sprint_report(standup_notes, SYSTEM_PROMPT)

    # ------------------------------------------------------------------
    # STEP 3: Print the AI report to terminal
    # ------------------------------------------------------------------
    print("\n📋  AI-GENERATED SPRINT STATUS REPORT")
    print("=" * 60)
    print(report)

    # ------------------------------------------------------------------
    # STEP 4: Save to markdown file for portfolio evidence
    # ------------------------------------------------------------------
    # Output filename is based on the input filename for easy tracking
    base_name = os.path.splitext(os.path.basename(input_file))[0]
    output_filename = f"{base_name}_report.md"

    with open(output_filename, "w", encoding="utf-8") as f:
        f.write(report)

    print("=" * 60)
    print(f"✅ Report saved to: {output_filename}")
    print("✅ AgileIQ report generation complete.")
    print("=" * 60)